apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm516-barramento-de-eventos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barramento-de-eventos
  template:
    metadata:
      labels:
        app: barramento-de-eventos
    spec:
      containers:
        - name: barramento-de-eventos
          image: igorims/ecm516-barramento-de-eventos
          resources:
            requests:
              memory: "512Mi"
              cpu: "2"
            limits:
              memory: "512Mi"
              cpu: "2"