apiVersion: v1
kind: Service
metadata:
  name: ecm516-barramento-de-eventos-service
spec:
  selector:
    app: barramento-de-eventos
  type: ClusterIP
  ports:
    - name: barramento-de-eventos
      protocol: TCP
      port: 10000
      targetPort: 10000
